// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itpdqwsltxufkiphteqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cGRxd3NsdHh1ZmtpcGh0ZXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODA2NDgsImV4cCI6MjA1OTI1NjY0OH0.VbkzDibBTZFjjsXkltt4zVXHnBaluBvsp4cyQMlKpiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);